### ISSUE TITLE
Money scale

### ISSUE THREAD

**Issue by stepanets** [elegant-bro/money#5]
> `scale` is more laconic

possibly

But Im still think `scale` is an object of another issue which implementation could help us solve current. Because Im sure we need some `Equals` class which must include scale in equality calculation.

_Originally posted by @anikeevda in https://github.com/elegant-bro/money/issues/4#issuecomment-581103632_

**Comment by stepanets** [comment]
We need scale() method, where should it lives?
`Currency::scale()`
`Money::scale()`

**Comment by stepanets** [comment]
@tigokr 
> what if `precision(): Precision`? that hides this complexity and which you can configure in equity requirements

What this object will do? Can you show some example?

**Comment by tigokr** [comment]
i can't do this right now, but imagine what you should provide some Precision object to your Equal method

**Comment by stepanets** [comment]
We had discussion with @anikeevda and made the conclusion that scale is required only in operations like multiply, add, etc. So we add scale to classes constructors where it's required and that's all. There will be no additional methods in the interface.

**Comment by anikeevda** [comment]
But idea was in general not good at all so we decided to move back to `scale` method in Money interface
